RENCI/APSViz-UI-V3

src/components/dialog/observation-chart.js
fixing the chart line when there is no data for that point
=> Chart updates

src/components/trays/layers/layer-card.js, src/context/map-context.js
this data field is now coming back in the layer properties. this uses a DB table to do the mapping of type to name in the stored function.
=> Removing the hard-code mapping of product type to product name.

src/components/map/default-layers.js
@lstillwe you observed a layer-ordering anomaly on May 8 in Slack; this PR aims to address that issue.
it seems that when the user reorders layers, the `defaultModelLayers` ordering updates in state as expected, but the layers don't get updated on the map.
as we know, we can force rerendering a component by manually changing its `key` prop. the `key` prop on those layer components was simply the index in the map/array traversal, which seemed sufficient to rerender things and keep them in sync. however, it was not. but it seems that adding a piece of data from the layer to the `key` seems to keep state and layers on the map in sync.
also, i think we were rendering them in the opposite stacking order. please verify! :grin:
=> [bugfix] layer ordering

src/components/control-panel/control-panel.js
the layer logic seems sensible. i took the liberty to tidy up some of the jsx and some of the styles.
=> tidy react

src/components/control-panel/control-panel.js
When cycling through model run cycles on the control panel, if the newly selected date/cycle already exists in the defaultModelLayers list, move those layer to the top of the list.
=> #51 Added logic to move existing layers to the top

src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js
This PR adds the plotting of "APS Forecast" data as well as some cosmetic tweaks.
if this PR is satisfactory, please merge and remove the branch upon approval.
=> Adding the plot of "APS Forecast" data

src/components/dialog/observation-dialog.js, src/components/map/default-layers.js, src/components/share/buildlink.js, src/components/share/share-comment.js, src/components/trays/layers/tray-contents.js, src/utils/map-utils.js
Adds a dialog to capture a share comment. also added a control to the layers tray that shows the comment.
This update requires at least 2 steps to test.
Creation of the share link
1. open the app.
2. select one or more observations 
3. hit the share button
4. in the dialog that appears put in a comment
5. then hit the create button.
6. this will have placed a URL in your cut/paste buffer. which you will use for...
Loading the share link
1. paste the url into your browser
2. behold the recreation of your share. including...
- your comment appearing in the "layers" tray.
- any observation dialogs recreated. if you chose >1 you will have to move them because they will overlap.
Here is an example share URL:
http://localhost:8080/#share=run_id:4378-2024041512-gfsforecast~comment=Look%20at%20the …
=> Capture/display a share comment.

src/components/dialog/observation-chart.js
adding reformatted x-axis labels, making sure UTC time is used everywhere in the chart.
see issue #119 
this may also correct issue #120 but needs to be verified.
=> correcting issue #119

src/components/map/default-layers.js, src/components/trays/model-selection/synopticTab.js, src/components/trays/model-selection/tropicalTab.js
this PR prevents the default and undesired behavior of refetching on window focus by adding a configuration variable  &mdash; `refetchOnWindowFocus: false` &mdash; to our three usages of `useQuery`. the issue this PR addresses, #125, only mentions the map refetching, but the model selection forms were also refetching, so those instances were also addressed here.
=> bugfix: map refetching data on window/tab focus

src/components/trays/layers/delete-layer-button.js, src/components/trays/layers/layer-card-actions.js, src/components/trays/layers/layer-card.js
merging this PR will move the delete button from the layer card's expanding panel to the summary portion of the layer card.
there's still lots of room for improvement with this layer list situation, and we can address in layer changes, but i've taken this opportunity to pull the delete layer button out to a separate component. the other code changes are basically trivial&mdash;moving stuff around and whatnot.
=> 126 move layer delete trash can to the layer panel

src/components/share/buildlink.js
=> adding user feedback after the creation of a share link.

src/components/trays/layers/delete-layer-button.js, src/components/trays/layers/form.js, src/components/trays/layers/list.js, src/components/trays/model-selection/catalogItems.js, src/context/map-context.js
This PR has code that will render selected models in groups on the layers tray.
addresses issue #130
=> Group by model runs on the layer tray

src/components/trays/layers/list.js
this addresses #147 
essentially, the solution is passing that `provided['dragHandleProps']` object to the component that we want to use for the handle, but you'll see i also tidied up some of the accordion structure
=> bugfix: layer group card drag handle

src/context/map-context.js
=> fixes issue #152 - default the layer visibility when model runs are deleted.

src/components/trays/layers/list.js
alterations to stop the "button in a button" console warnings.
=> #157 layer tray console warnings

src/components/control-panel/control-panel.js, src/components/trays/layers/list.js, src/components/trays/model-selection/catalogItems.js, src/components/trays/remove/index.js, src/components/trays/remove/remove-observations.js, src/context/map-context.js
addresses #56 
when the observations are toggled on the control panel, all open obs dialogs and "target" overlays are removed.
=> #56-Remove selected observation data from state

src/components/trays/model-selection/catalogItems.js, src/components/trays/model-selection/synopticTab.js
Added a bunch of code (after a bunch of investigation/testing) to handle the calendar control validation.
note that the previous UI did not allow manually entering dates, this one does. so there a lot more test conditions to go through. 
if you find a error please take note of the steps to reproduce and let me know. i am still finding issues as i continue my testing. there are a number of console.log() statements (that are commented out) that may help in troubleshooting.
=> #91 Date picker error handling

src/components/sidebar/sidebar.js
the sidebar menu items are currently collected at the top. i think it makes to separate certain menu items. namely, i think settings and help could drift to the lower portion of the sidebar.
this PR brings in a proposed approach that results in something like the screenshot below.
=> separate sidebar menu items

src/components/map/adcirc-raster-layer.js, src/components/map/default-layers.js
Fixed blinking by tinkering some more with the ids
=> #183 Fixed blinking by tinkering some more with the ids

package-lock.json, package.json
geostyler-sld-parser has issued a new release (6.1.2) so the UI has been updated to use it.
this addresses the high severity vulnerability.
=> #185 upgraded version of geostyler-sld-parser

package-lock.json
addresses issue #187 
Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS
=> fixing webpack vulnerability

src/components/control-panel/control-panel.js
Added code to force an update of the filters for useQuery
Created new issue:  #189 to restrict user from cycling through runs on the control panel too quickly.
=> Fix for Issue150

src/components/legend/legend.js, src/utils/default-styles.js
changed maxele colormap to have only 10 intervals
updated colormap was provided by B. Blanton.
NOTE: in order to get the new default style, you must click the reset layer colormaps button on the side panel trashcan icon
=> Issue181 - change maxele colormap to have only 10 intervals

src/components/legend/legend.js, src/components/trays/compare-layers/CompareLayersTray.js, src/components/trays/layers/layer-card.js, src/context/map-context.js
Addresses issue #204.
Note: A bug was discovered when assessing this functionality.
there appears to be other opportunities for this functionality that use the mapstyle to determine the icon type.
=> Merge functionality to get layer type icons.

src/components/trays/layers/list.js
as the title says...
this also had the negative effect of suppressing the reordering of layers in the model run.
=> #209 Removing the sorting of layers in a selected model run

src/context/map-context.js
=> adding the hi-res water level icon to the list of icons <-> product types.

src/components/control-panel/control-panel.js, src/components/legend/legend.js
adjusting the z-indexes of the legend and control panel to be:
- under the tray, 
- under the compare panel selections,
- over the compare slider control,
- a peer to the observation dialogs.
=> adjusting the z-indexes

src/components/compare-panel/compare-panel.js
addresses issue #246 
adding more checks to avoid crashes when a selected compare model/layer is deleted.
=> Adding checks to avoid a crash whilst in compare mode

src/components/trays/model-selection/catalogItems.js
addresses issue #265 
missed this one in the original update
=> Issue 265 use common data header

src/components/trays/help-about/helpAboutTray.js
=> Issue 271 - Adding help/about FAQs for the new colormap functionality.

src/utils/map-utils.js
this addresses part 2 of issue #288 .
currently only the RENCI dev and prod deployments have the DB SP and UI data web services to test this.
=> forcing the nopp default layers to use the 'coampsforecast' ensemble name

src/components/control-panel/branding.js, src/utils/map-utils.js
addresses issue #292 
altering the way the project code is collected so the nopp logo is found
=> Fixing the missing NOPP logo

package-lock.json, package.json, src/components/legend/legend.js, src/components/trays/settings/colormaps/colormap-slider.js, src/components/trays/settings/colormaps/style-edit.js, src/components/trays/settings/colormaps/utils.js
Fixed top end data values missing when selecting intervals colormap type
Also addressed issues with upper and lower bound sliders
=> Issue278 - Fixed top end data values missing when selecting intervals colormap type

src/app.js, src/components/alert-user/alert-user.js, src/components/alert-user/index.js, src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js, src/components/dialog/observation-dialog.js, src/components/map/adcirc-raster-layer.js, src/components/map/default-layers.js, src/context/map-context.js, webpack.config.js
this addresses issue  #273 
implementation of the geo-point timeseries data/dialog. 
note that you will need to use an updated UI data web service component for this to work (currently in dev).
=> Timeseries extract

src/components/map/adcirc-raster-layer.js
=> Adding a check to do nothing if the point was already selected

src/components/map/adcirc-raster-layer.js, src/components/side-by-side/leaflet-side-by-side.js
addresses issue #304 
this PR adds generalization of the TDS URL so it works across all namespace implementations.
=> Generalize tds url

package-lock.json, package.json, src/components/dialog/observation-chart.js, src/components/map/adcirc-raster-layer.js
addresses Issue #306
better error handling/reporting textual error back to the user 
also snuck in a change to the dialog title for geo-points
=> Better geo-point data error handling

package-lock.json, src/app.js, src/components/alert-user/alert-user.js, src/components/config/config.js, src/components/config/index.js, src/components/control-panel/control-panel.js, src/components/map/adcirc-raster-layer.js, src/components/map/default-layers.js, src/context/map-context.js, webpack.config.js
this addresses an issue in #288  , #302
this is a implementation of getting/setting/resetting (via a UI data web-service) the default instance name to use when the app starts up. there are a number of things to test in this update as it spans:
- numerous aspects of the UI initial data gathering of map and control-panel data.
- the UI Data app that set/gets/resets the default startup instance name.
it also addresses bugs/tidying up in some other unrelated code discovered in testing. such as:
- improving the tool-tip text on the alert popup.
- not allowing geo-point selection whilst in compare mode.
- bug in adcirc-raster-layer.js when no product type is set for the current opacity setting.
- minor refactoring for code readability and comments.
=> Default instance name at startup

src/components/dialog/base-floating-dialog.js, src/context/map-context.js
addresses issue #322 
adds functionality to allow the user to select a dialog from a stack of dialogs to bring it up to the foreground (focus).
=> Tracks the obs dialog that has focus

src/components/map/hurricane-track.js, src/components/trays/settings/colormaps/colormap-slider.js, src/components/trays/settings/colormaps/data-range.js, src/components/trays/settings/colormaps/style-edit.js, src/components/trays/settings/colormaps/utils.js, src/components/trays/settings/index.js, src/components/trays/settings/units.js, src/context/settings.js, src/utils/default-styles.js, src/utils/map-utils.js
This PR adds a section to the settings panel to set unit of measurement to metric (default) or imperial.
The changes to the setting should mainly be visible in the legends and the ADCIRC raster settings functionality.
The units settings are persistent and will survive web page refresh.
One thing to note is that if the user switches between the metric and imperial settings, new default styles will be set for either one. All previously set ADCIRC raster setting will be lost and have to be reset.
=> Issue 296 field units

src/components/dialog/observation-chart.js, src/components/trays/help-about/helpAboutTray.js
Addresses issue #327 
this PR implements the rendering of user selected units of measurement on observation/geo-point charts as well as a new help/about FAQ.
=> Units of measurement for the chart
