RENCI/APSViz-UI-V3

src/components/help-about/helpAboutTray.js, src/components/model-selection/modelSelectionTray.js, src/components/trays/help_about/help_about.js, src/components/trays/help_about/index.js, src/components/trays/index.js, src/components/trays/model-selection/model-selection.js, webpack.config.js
Adding a help/about tray to put, among other things (eventually), the app version.
Please remove the branch after the merge.
=> Adding a help/about tray

src/components/control-panel/control-panel.js
just some minor fixes to remove warnings and repair the unique key for a looped control.
=> unique key for a looped control

src/components/help-about/helpAboutTray.js
meant to start a conversation...
=> adding some FAQs to consider.

src/components/model-selection/catalogItems.js
=> adding opacity to the layer properties

src/components/trays/layers/layer-card.js
the date format adopts the format used in all the other components (YYYY-MM-DD).
adjusting the opacity of the switch control so it is easier to see the selected state
=> Minor tweaks to the layer cards

src/components/trays/model-selection/catalogItems.js
like the title says.
if this PR is satisfactory, please merge and remove the branch.
=> adding meteorlogical model to the model select data label

package-lock.json, package.json
First one to look this over gets the privilege to merge it and remove the branch.
Set phasers on stun and good luck.
=> Addressing the GH reported vulnerability (CVE-2024-37890)

src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js, src/components/share/buildlink.js, src/components/share/share.js, src/components/trays/model-selection/catalogItems.js, src/components/trays/settings/index.js, src/context/settings.js
addresses issue #119 . also includes some data checking and other UI tweaks.
if satisfactory, please merge and optionally delete the branch.
thanks!
=> Issue 119 - Chart reformatting

src/components/dialog/observation-chart.js, src/components/trays/settings/index.js, src/context/settings.js
making the y-axis bounds data based and centered around 0.
=> Issue 119 - final updates to the chart

package-lock.json, package.json, src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js
this addresses issue #38 
Draft for now. i am not entirely impressed with the resize package i used,
=> #38 resizeable obs dialog

package-lock.json, package.json, src/components/sidebar/tray.js, src/components/trays/layers/delete-layer-button.js, src/components/trays/layers/list.js, src/components/trays/model-selection/catalogItems.js
addresses issue #136 and adds drag/drop reordering of model runs in the layers tray
=> #136 drag layer models

src/components/legend/legend.js, src/components/map/default-layers.js
Not sure if this ia temporary update of not - Brian has not yet indicated.
Brian wanted an update to the maxele style to be 0-2.25 for the maxele layer.
I have also pushed 2 new styles to the AWS and eds-dev environment GeoServers
=> updated style for hurricane Debby

src/components/dialog/observation-chart.js
like the title says. the dotted line makes it look bad for data currently under review.
=> changing all lines in the obs chart to solid.

src/components/dialog/observation-chart.js
=> adjusting chart line colors and thickness

src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js, src/components/dialog/observation-dialog.js
this PR represents a solution for issue #145
=> #145 obs chart line toggle

src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js
=> #156 Button wrap in the obs dialog when resizing

src/components/legend/legend.js
This PR addresses issue #154 .
=> #154 legend drag resize

src/components/dialog/base-floating-dialog.js, src/components/legend/legend.js
tweaking the min/max/default sizes, making the dialog title word wrap.
=> improvements to the way the resize control is configured.

package-lock.json, package.json
like the title says. addresses issue #165 
installing this will require a "npm install" to update the axios package in your local environment.
=> Upping to version of axios to handle the SSRF vulnerability issue

src/components/control-panel/control-panel.js
=> #169-correcting spelling mistake

src/components/trays/help-about/helpAboutTray.js
=> #171 - adding text, formatting to the help/about tray area.

src/components/sidebar/sidebar.js
this fixes the bug that arose from PR #178 .
=> track active tray with key

src/components/control-panel/control-panel.js
As requested by Brian, added subtle instance name to the control panel.
=> added instance name to control panel

src/components/control-panel/control-panel.js, src/components/legend/legend.js, src/components/map/default-layers.js, src/components/trays/remove/index.js, src/components/trays/remove/reset-styles.js
fixed the re-render when moving layers around in defaultModelLayer list
also added button to reset styles
add fixed problem with legend not dissapearing when no raster layer is selected
=> fixed the re-render when moving layers around

src/components/trays/model-selection/catalogItems.js, src/components/trays/model-selection/synopticTab.js, src/components/trays/model-selection/tropicalTab.js
trivial PR. just lowering font sizes on the model selection tray
=> Lowering fontsizes

src/components/trays/model-selection/catalogItems.js, src/components/trays/model-selection/synopticTab.js, src/components/trays/model-selection/tropicalTab.js
this addresses issue #128.
also, while doing this i noticed (and repaired):
- the results werent filtering on the instance name when selected.
- duplicate record limit param was being passed to the UI data web service for synoptic requests.
thanks to Shintaro for his observations and suggestions on this one.
=> #128 adding details to model selection results ++

src/components/trays/remove/remove-models.js, src/context/map-context.js
=> #198 - Remove all model runs

src/utils/default-styles.js
Updated colormap with new one provided by bblanton.
In order to update your UI with this colormap, must select remove icon from sidebar and then "Reset ADCIRC Layer Colormaps"
Then do a hard refresh of the website.
Please merge and delete branch on completion of review
=> #200 updated colormap spec for maxele as provided by bblanton

src/components/control-panel/control-panel.js, src/components/dialog/base-floating-dialog.js, src/components/legend/legend.js, src/components/sidebar/sidebar.js, src/components/sidebar/tray.js, src/components/trays/model-selection/DropDownOptions.js, src/components/trays/model-selection/tropicalTab.js
addresses issue #203 
the side/side compare slider (hard-coded z-index of 998) is now above the map layers and below everything else.
=> updated the z-indexing

src/components/sidebar/sidebar.js
addresses issue #219 
adjusting the z-index of the sidebar so it is above the sliding tray.
=> adjusting the z-index of the sidebar

package-lock.json, package.json, src/components/trays/help-about/helpAboutTray.js
=> Issue 234 - add the hires info to help

src/components/trays/layers/list.js
added check for zero length hurricane layers array
=> fixed check for hurricane layers when dragging layers in layers list

src/components/control-panel/control-panel.js, src/components/trays/help-about/helpAboutTray.js, src/components/trays/layers/layer-card.js, src/components/trays/layers/list.js
addresses issue #244 
forcing the sorting of layers in the selected layers tray and control panel.
also adding tool tips for the layer buttons on the control panel. thought it would be nice.
=> Issue 244 layer ordering

src/components/map/adcirc-raster-layer.js
This PR fixes the broken opacity controller.
Please merge and delete branch when approved. Thank you!
=> Issue248 - this fixes the broken opacity controller

src/components/sidebar/menu-item.js
=> conditionally render menu item tooltips

src/components/dialog/base-floating-dialog.js, src/components/dialog/observation-chart.js, src/components/legend/legend.js
addresses issue #253 
making the draggable components
- stay within the map surface boundaries, 
- redoing component min/max re-sizeable limits 
- lowering font sizes
=> issue 253 - Making the draggable components stay within the map surface boundaries

src/components/compare-panel/compare-panel.js, src/components/trays/compare-layers/CompareLayersTray.js, src/context/map-context.js
Addresses #261 
couple of things:
- handling the resetting/restoring of the view when entering into and out of the compare mode
- tweaks to the compare views (top panel, tray)
=> Issue 261 compare cleanup

src/components/control-panel/control-panel.js
=> issue 277 - adding the event type information to the panel.

src/components/trays/model-selection/synopticTab.js, src/components/trays/model-selection/tropicalTab.js
Addresses issue #297
Removing the clearing of the date in state because that is handled in the control itself.
=> Model selection - Correcting the date handling

src/components/map/adcirc-raster-layer.js
=> Compare mode alert removal

src/components/dialog/observation-chart.js
This is for my development only when troubleshooting using  a locally running version of the UI data app.
this would be a no-op in linux based environments.
=> Removing windows line endings from CSV data
